name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Choose environment to deploy code'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

  repository_dispatch:
    types: [Automation-wf]

permissions:
  id-token: write
  contents: read

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Print github event context (for debugging)
        run: echo "${{ toJson(github.event) }}"

      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "ENVIRONMENT=${{ github.event.inputs.ENV }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_EVENT_NAME}" == "repository_dispatch" ]]; then
            echo "ENVIRONMENT=${{ github.event.client_payload.ENV }}" >> $GITHUB_ENV
          else
            echo "Unknown trigger"
            exit 1
          fi  # Add this fi to close the if-else block

      - name: Show chosen environment
        run: echo "The selected environment is $ENVIRONMENT"
