name: CI/CD Pipeline

on:
  repository_dispatch:
    types: [Automation-wf]

permissions:
  id-token: write
  contents: read

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Print github event context (for debugging)
        run: echo "${{ toJson(github.event) }}"
        
      - name: Show chosen environment
        run: echo "The selected environment is ${{ github.event.client_payload.ENV }}"
