name: CI/CD Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Automation-wf]
    inputs:
      ENV:
        description: 'Choose environment to deploy code'
        required: true
        default: 'stage'
        type: choice
        options:
          - dev
          - stage
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Show Environment
        run: echo "The selected environment is ${{ github.event.inputs.ENV }}"
